"""empty message

Revision ID: 23a31b54a0a3
Revises: 40fcf98bde4c
Create Date: 2024-06-22 22:22:45.975752

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23a31b54a0a3'
down_revision: Union[str, None] = '40fcf98bde4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    dialect = conn.dialect.name
    if dialect != "sqlite":

        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('streams', 'temperature',
                   existing_type=sa.INTEGER(),
                   type_=sa.Float(),
                   existing_nullable=False)
        # ### end Alembic commands ###

        # Update existing temperature values by dividing them by 100
        op.execute('UPDATE streams SET temperature = temperature / 100.0')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streams', 'temperature',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
