"""added fields to feeback

Revision ID: 2592138760af
Revises: 92ecafbb1549
Create Date: 2024-12-11 11:23:31.861199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2592138760af'
down_revision: Union[str, None] = '92ecafbb1549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create Enum types explicitly first in the database
    op.execute("CREATE TYPE feedbacktype AS ENUM ('chat', 'evaluations')")
    op.execute("CREATE TYPE feedbackpositives AS ENUM ('clair', 'synthetique', 'complet', 'sources_fiables')")
    op.execute("CREATE TYPE feedbacknegatives AS ENUM ('incorrect', 'incoherent', 'manque_de_sources')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('type', sa.Enum('chat', 'evaluations', name='feedbacktype'), nullable=False))
    op.add_column('feedbacks', sa.Column('note', sa.Integer(), nullable=True, comment='Note from 0 to 5'))
    op.add_column('feedbacks', sa.Column('positives', sa.Enum('clair', 'synthetique', 'complet', 'sources_fiables', name='feedbackpositives'), nullable=True))
    op.add_column('feedbacks', sa.Column('negatives', sa.Enum('incorrect', 'incoherent', 'manque_de_sources', name='feedbacknegatives'), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'negatives')
    op.drop_column('feedbacks', 'positives')
    op.drop_column('feedbacks', 'note')
    op.drop_column('feedbacks', 'type')
    # ### end Alembic commands ###
