"""empty message

Revision ID: 40fcf98bde4c
Revises: eff9bf7b048e
Create Date: 2024-05-31 18:19:45.785909

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40fcf98bde4c'
down_revision: Union[str, None] = 'eff9bf7b048e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    dialect = conn.dialect.name

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_cookie', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('accept_retrain', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_organization_name'), 'users', ['organization_name'], unique=False)
    # ### end Alembic commands ###

    if dialect != "sqlite":
        # Manual
        op.execute("UPDATE users SET accept_cookie = false WHERE accept_cookie IS NULL")
        op.execute("UPDATE users SET accept_retrain = false WHERE accept_retrain IS NULL")
        op.alter_column('users', 'accept_cookie', nullable=False)
        op.alter_column('users', 'accept_retrain', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_name'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'accept_retrain')
    op.drop_column('users', 'accept_cookie')
    # ### end Alembic commands ###
