"""Third revision

Revision ID: 4ad236ae1213
Revises: 324c40362d79
Create Date: 2023-11-06 14:40:40.571862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad236ae1213'
down_revision: Union[str, None] = '324c40362d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.add_column('streams', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'streams', 'chats', ['chat_id'], ['id'])
    op.create_check_constraint('_streams_user_id_chat_id_cc', 'streams', '(user_id IS NULL OR chat_id IS NULL) AND (user_id IS NOT NULL OR chat_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_streams_user_id_chat_id_cc', 'streams', type_='check')
    op.drop_constraint(None, 'streams', type_='foreignkey')
    op.drop_column('streams', 'chat_id')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
