"""v4_fix

Revision ID: 8e2a9a682bab
Revises: 2f54c357b7fe
Create Date: 2024-01-10 15:53:17.717734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2a9a682bab'
down_revision: Union[str, None] = '2f54c357b7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_constraint('_streams_user_id_chat_id_cc', 'streams', type_='check')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.create_check_constraint('_streams_user_id_chat_id_cc', 'streams', '(user_id IS NULL OR chat_id IS NULL) AND (user_id IS NOT NULL OR chat_id IS NOT NULL)')
