"""Update chat model with operators as JSON

Revision ID: 92ecafbb1549
Revises: 8c1a759aa16f
Create Date: 2024-11-15 13:09:52.572747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ecafbb1549'
down_revision: Union[str, None] = '8c1a759aa16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('operators', sa.JSON(), nullable=True))
    op.drop_column('chats', 'operator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'operators')
    # ### end Alembic commands ###
