"""V5

Revision ID: 0af622cc7d70
Revises: 8e2a9a682bab
Create Date: 2024-02-06 15:31:56.202879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af622cc7d70'
down_revision: Union[str, None] = '8e2a9a682bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('postprocessing', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'postprocessing')
    # ### end Alembic commands ###
