"""v3.1

Revision ID: 8079b4c73914
Revises: 7c2f9941f8da
Create Date: 2024-01-08 13:07:29.701336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8079b4c73914'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('streams', sa.Column('rag_sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'rag_sources')
    op.drop_column('streams', 'response')
    # ### end Alembic commands ###
