version: '3.8'
services:
  db:
    image: postgres:16.0-alpine
    container_name: albert-postgres-db-dev
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
