# DO NOT EDIT

INSTITUTIONS = [
    "115",
    "119",
    "3939",
    "ACTION LOGEMENT",
    "ADEME",
    "AGENCE POLE EMPLOI (APE)",
    "AGIRC-ARRCO",
    "ANAH",
    "ANEF (Administration Numérique des Français de l'Etranger)",
    "ANTAI",
    "ANTS",
    "Administration territoriale de l'Etat",
    "Afpa Accès à l'Emploi",
    "Agence Comptable ASP",
    "Agence Nationale des Fréquences (ANFR)",
    "Agence de la biomédecine (registre national des refus de don d’organes)",
    "Agence de services et de paiement (ASP)",
    "Agence nationale pour l'amélioration des conditions de travail (Anact)",
    "Aides aux véhicules",
    "Amendes.gouv.fr",
    "Archives départementales",
    "Archives nationales",
    "Ars",
    "Assurance retraite Ile de France",
    "Autorisations d'urbanisme",
    "Bibliothèques nationales",
    "Bloctel",
    "Brigade de gendarmerie",
    "Bureau de douane",
    "CADA (commission d'accès aux documents administratifs)",
    "CAF",
    "CAISSE NATIONALE MILITAIRE DE SECURITE SOCIALE",
    "CAMIEG : Caisse d'assurance maladie des industries électriques et gazières",
    "CCMSA",
    "CCSP",
    "CGSS Assurance Maladie",
    "CGSS RETRAITE",
    "CIPAV",
    "CNAF",
    "CNAM",
    "CNAREFE",
    "CNAV",
    "CNIL",
    "COMMISSARIAT DE POLICE",
    "COMMISSARIAT DE POLICE DE PROXIMITE",
    "CONSEIL DES PRUD'HOMMES",
    "COUR D'APPEL",
    "CPAM",
    "CROUS",
    "Cadastre.gouv.fr",
    "Caisse des Français de l’étranger (CFE)",
    "Caisse des dépôts (CDC)",
    "Caisse nationale de retraites des agents des collectivités locales (CNRACL)",
    "Caisse nationale de solidarité pour l'autonomie (CNSA)",
    "Caisse régionale URSSAF",
    "Candilib",
    "Carsat",
    "Casier judiciaire national",
    "Cdg",
    "Centre des Impôts Foncier",
    "Centre du service national et de la jeunesse",
    "Centre national CESU",
    "Centre national PAJEMPLOI",
    "Centre national TESE",
    "Chambre de commerce et d'industrie (CCI)",
    "Chambre_agriculture",
    "Chambre_metier",
    "Chorus Pro",
    "Chèque énergie",
    "Collectivités territoriales - Communes",
    "Collectivités territoriales - Départements",
    "Collectivités territoriales - Régions",
    "Compte association",
    "Conseils départementaux de l'accès au droit",
    "Crit'air",
    "DEAL",
    "DGAC",
    "DGAFP",
    "DGCCRF",
    "DGDDI",
    "DGFIP",
    "DIR DEPT FINANCES PUBLIQUES",
    "DIR REGION FINANCES PUBLIQUES",
    "DIRECTION DE LA SECURITE DE PROXIMITE DE L’AGGLOMERATION PARISIENNE",
    "DIRECTION OU SERVICE ACTIF DE LA DGPN",
    "DITP",
    "DR POLE EMPLOI",
    "DREAL",
    "DSDEN",
    "Defenseur des droits",
    "Demande-logement-social.gouv.fr",
    "Direccte",
    "Direction Générale des Entreprises (DGE)",
    "Direction de l'administration pénitentiaire",
    "Direction de l'information légale et administration publique (DILA)",
    "Direction des impôts des non résidents",
    "Direction des services judiciaires",
    "Direction départementale de l'emploi, du travail et des solidarités",
    "Direction départementale des territoires",
    "Direction interministérielle du Numérique (DINUM)",
    "Direction interrégionale DI",
    "Direction régionale de l'alimentation, de l'agriculture et de la forêt (DRAAF)",
    "Direction régionale des douanes",
    "Démarches simpliées",
    "ETABLISSEMENT HOSPITALIER",
    "Ensap.gouv.fr",
    "Etablissement Français du Sang",
    "Etablissement pénitentiaire",
    "Etablissements spectacle vivant",
    "Formulaire de contact Police Nationale",
    "France services",
    "FranceAgriMer",
    "FranceRenov'",
    "Franceconnect",
    "Gendarmerie Nationale",
    "Guichet unique navigation GUN",
    "HOTEL DE POLICE",
    "Histovec",
    "I-CAD",
    "INPI - Institut National de la Propriété Industrielle",
    "INSEE",
    "Impots.gouv.fr",
    "Impôts entreprises étrangères",
    "Info Retraite",
    "Infos Douane Service IDS",
    "Institut Français du Cheval et de l'Equitation (IFCE)",
    "Intérieur.gouv.fr",
    "Ircantec",
    "Journal Officiel",
    "Juridiction administrative",
    "LES CROUS",
    "MDPAAD",
    "MDPH-MDA",
    "MSA",
    "MTE-MCTRCT",
    "Maprim'renov",
    "Maprocuration.gouv.fr",
    "Masecurite.fr",
    "Mesdroitssociaux.gouv.fr",
    "Messervices.etudiant.gouv.fr",
    "Ministère de l'Agriculture et de l'Alimentation",
    "Ministère de la Culture",
    "Ministère de la Justice",
    "Ministère de la Mer",
    "Ministère de l’Europe et des Affaires étrangères (MEAE)",
    "Ministère des Armées",
    "Ministère des Solidarités et de la Santé",
    "Ministère du Travail, de l'Emploi et de l'Insertion",
    "Monuments nationaux",
    "Musées nationaux et assimilés",
    "Médiateur des communications électroniques",
    "Médiateur national de l'énergie",
    "Numéro d’assistance des particuliers",
    "Numéro vert covid",
    "OFFICIER DU MINISTERE PUBLIC",
    "OFII",
    "ONaCVG",
    "OPCO",
    "Office français de protection des réfugiés et apatrides (OFPRA)",
    "Onf",
    "Opération tranquillité vacances (OTV)",
    "Oups.gouv.fr",
    "PHAROS",
    "PLACE – Plateforme d’achat de l’Etat",
    "POLE EMPLOI",
    "POLICE NATIONALE",
    "PREFECTURE DE POLICE DE PARIS",
    "Paierie départementale",
    "Paierie régionale",
    "Parrainage.refugies.info",
    "Pass Culture",
    "PayFip.gouv.fr",
    "Point-justice (MJD)",
    "Point-justice (PAD)",
    "Police Municipale",
    "Portail de l'Alternance",
    "Portails en ligne",
    "Pré-plainte en ligne (PPEL)",
    "Préfecture",
    "Pôle d'action économique PAE",
    "Pôle de recouvrement spécialisé",
    "RAFP",
    "Rectorat",
    "Referendum.interieur.gouv.fr",
    "Retraitesdeletat.gouv.fr",
    "Région de Gendarmerie",
    "Réseau consulaire",
    "Réseau des rectorats et DSDEN",
    "Réseau hors réseau",
    "SARVI (service d'aide au recouvrement des victimes)",
    "SERVICES NUMERIQUES DE LA POLICE NATIONALE",
    "SGMAS",
    "Service Central d'Etat Civil",
    "Service de gestion comptable",
    "Service de publicité foncière",
    "Service des Impôts des entreprises",
    "Service des Impôts des particuliers",
    "Service des Impôts des particuliers et des entreprises",
    "Service des autorisations de mouvements internationaux d'armes SAMIA",
    "Service départemental de l'enregistrement",
    "Service en ligne Ma Sécurité",
    "Service en ligne Perceval",
    "Service-public.fr",
    "Services Publics +",
    "Services du Premier Ministre",
    "Services numériques du ministère de l'Intérieur",
    "Services électoraux",
    "SignalConso",
    "Signalement.gouv",
    "Signalements violences sexuelles et sexistes (VSS)",
    "Site de démarches en ligne du MAA",
    "Sous-préfecture",
    "Structure France services",
    "TA",
    "THESEE",
    "TRIBUNAL DE PROXIMITE",
    "TRIBUNAL JUDICIAIRE",
    "Telepac",
    "Timbres.impots.gouv.fr",
    "Tous Anti Covid",
    "Tribunal Commerce",
    "Trésorerie",
    "Trésorerie amendes",
    "Trésorerie hospitalière",
    "Trésorerie spécialisée",
    "TéléRC",
    "Télépoint",
    "URSSAF",
    "Unité Numérique",
    "Université",
    "Universités et écoles",
    "Ville - Commune",
    "Viticulture et contributions indirectes",
    "Www.guichet-entreprises.fr",
    "gouvernement.fr",
    "monprojetanah",
    "prix-carburants.gouv.fr",
    "servicesalapersonne.gouv.fr",
    "stationnement.gouv.fr",
    "Établissement d'enseignement supérieur et de recherche",
]
