version: "3.8"

services:  
  api:
    image: albert/api:latest
    restart: always
    environment:
      - APP_VERSION=1.0.0
      - MODELS_URLS="['http://localhost:8080']"
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_PASSWORD=changeme
      - QDRANT_HOST=qdrant
      - QDRANT_GRPC_PORT=6334
      - QDRANT_REST_PORT=6333
      - POSTGRES_URI=postgresql://postgres:changeme@postgres:5432/postgres
      - CONTACT_EMAIL=contact@changeme.com
      - BACKEND_CORS_ORIGINS="*"
      - API_WHITELIST_FILE=pyalbert/config/whitelist_config.json
      - API_URL=http://localhost:8000
      - REDIS_HOST=http://localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=changeme
    ports:
      - 8000:8090
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
